### ISSUE TITLE
Support variables

### ISSUE THREAD

**Issue by 54nn0n** [apirak/visible-property-2#3]
It would be really neat if this could support variables (and anything that it's related to) too!

**Comment by apirak** [comment]
Now fill and stroke support Variable already 🎉 

![Screenshot 2024-05-10 at 22 16 46](https://github.com/apirak/visible-property-2/assets/79386/e8769687-7d91-4788-aba8-c8b426b28745)

It also show the link between Variable too

**Comment by 54nn0n** [comment]
Amazing work! Thank you so much!
