### ISSUE TITLE
Percentage and Opacity value is missing

### ISSUE THREAD

**Issue by gialluz** [apirak/visible-property-2#4]
Hello, I want report two small issues:

- missing Percentage symbol for HSL / HSB
- missing Opacity value

<img width="390" alt="image" src="https://github.com/apirak/visible-property-2/assets/143732419/0f15a013-1abb-4063-8b3b-d41a877141b7">

**Comment by apirak** [comment]
For opacity 
- The current version show opacity value automatic when we use it and hide for non.

![Screenshot 2024-05-10 at 22 24 05](https://github.com/apirak/visible-property-2/assets/79386/57047488-7aed-4e70-bfe4-d82b69724e9c)

For Percentage symbol 
- I will show % only for last two value follow w3school

![Screenshot 2024-05-10 at 22 25 10](https://github.com/apirak/visible-property-2/assets/79386/d0a2811a-6a8d-41c1-a0ef-f864c35d7f59)
